# Generated by Django 4.2.6 on 2023-11-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_remove_crypto_id_remove_crypto_title_crypto_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='key',
            new_name='id',
        ),
    ]
