# Generated by Django 4.2.6 on 2023-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_rename_key_crypto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='id',
            new_name='key',
        ),
        migrations.AddField(
            model_name='crypto',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
