# Generated by Django 4.2.6 on 2023-11-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_rename_id_crypto_key_crypto_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='rank',
            field=models.SmallIntegerField(default=0),
        ),
    ]
